"""a = int(input())
b = int(input())
x = a*int(str(b)[-1])
y = a*int(str(b)[-2])
z = a*int(str(b)[-3])
print(x)
print(y)
print(z)
print(x+(y*10)+(z*100))"""
a = int(input())
b = input()
print(a*int(b[-1]))
print(a*int(b[-2]))
print(a*int(b[-3]))
print(a*int(b))
